# Used modules below...
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
---
- name: Provision EC2 with bare-minimum packages and install Nginx
  hosts: all
  gather_facts: false
  connection: ssh
  become: yes
  vars:
    NODEJS_VERSION: "23"
  tasks:
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip

    - name: Ensure botocore and boto3 modules are installed
      ansible.builtin.pip:
        name: ["boto3", "botocore"]
        extra_args: "--user"

    - name: Run NodeSource setup script directly
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_23.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Verify Node.js installation
      ansible.builtin.shell: "node -v"
      register: node_version
      ignore_errors: yes

    - name: Print Node.js version
      ansible.builtin.debug:
        msg: "Node.js version installed: {{ node_version.stdout }}"

    - name: Clean up NodeSource setup script
      ansible.builtin.file:
        path: /tmp/nodesource_setup.sh
        state: absent

    - name: Ensure npm is installed or updated
      ansible.builtin.shell: "npm install -g npm@latest"
      args:
        executable: /bin/bash

    - name: Verify npm installation
      ansible.builtin.shell: "npm -v"
      register: npm_version
      ignore_errors: yes

    - name: Print npm version
      ansible.builtin.debug:
        msg: "npm version installed: {{ npm_version.stdout }}"

    # - name: Update the repository cache and update package "nginx" to latest version
    #   ansible.builtin.apt:
    #     name: nginx
    #     state: latest

    # - name: Start Nginx
    #   ansible.builtin.service:
    #     name: nginx
    #     state: started
    #     enabled: yes

    - name: Install necessary Linux packages
      ansible.builtin.apt:
        name:
          - zip
          - unzip
          - findutils
        state: present

    - name: Install "pm2" - process manager for Node.JS
      community.general.npm:
        name: pm2
        global: true

    - name: Verify pm2 installation
      ansible.builtin.shell: "pm2 -V"
      register: pm2_version
      ignore_errors: yes

    - name: Print pm2 version
      ansible.builtin.debug:
        msg: "pm2 version installed: {{ pm2_version.stdout }}"
